# Generated by Django 4.2.10 on 2024-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automatizacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="control_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("fecha", models.CharField(max_length=100)),
                ("control_data", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Cliente", models.CharField(max_length=100)),
                ("Fecha_carga", models.DateTimeField()),
                ("DB_information", models.JSONField()),
            ],
            options={
                "db_table": "data_sensor",
            },
        ),
        migrations.AlterField(
            model_name="data",
            name="clave",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="data",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
